apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-a-monitor
  namespace: pspd
  labels:
    app: a
    release: prometheus
spec:
  selector:
    matchLabels:
      app: a
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
