apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-p-metrics
  namespace: pspd
  labels:
    app: p
    release: prometheus
spec:
  selector:
    matchLabels:
      app: p
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scheme: http
