apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-deploy
  namespace: pspd
spec:
  replicas: 1
  selector: { matchLabels: { app: b } }
  template:
    metadata: 
      labels: 
        app: b
        version: v1
        scenario: resources
    spec:
      containers:
        - name: b
          image: b-service:local
          imagePullPolicy: IfNotPresent
          ports: 
            - { containerPort: 50052, name: grpc }
            - { containerPort: 9102, name: metrics }
          env:
            - { name: PORT, value: "50052" }
            - { name: METRICS_PORT, value: "9102" }
          resources:
            # ALTERADO: Recursos reduzidos (stress test)
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe: { tcpSocket: { port: 50052 }, initialDelaySeconds: 2, periodSeconds: 5 }
          livenessProbe:  { tcpSocket: { port: 50052 }, initialDelaySeconds: 5, periodSeconds: 10 }
---
apiVersion: v1
kind: Service
metadata:
  name: b-svc
  namespace: pspd
  labels:
    app: b
spec:
  selector: { app: b }
  ports: 
    - { port: 50052, targetPort: 50052, name: grpc }
    - { port: 9102, targetPort: 9102, name: metrics }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: b-hpa
  namespace: pspd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: b-deploy
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
