apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-rest-deploy
  namespace: pspd
spec:
  replicas: 1
  selector: { matchLabels: { app: a-rest } }
  template:
    metadata: { labels: { app: a-rest } }
    spec:
      containers:
        - name: a-rest
          image: a-rest-service:local
          imagePullPolicy: IfNotPresent
          ports: [ { containerPort: 8000 } ]
          readinessProbe: { httpGet: { path: /a/hello, port: 8000 }, initialDelaySeconds: 3, periodSeconds: 5, failureThreshold: 10 }
          livenessProbe:  { httpGet: { path: /a/hello, port: 8000 }, initialDelaySeconds: 5, periodSeconds: 10, failureThreshold: 10 }
---
apiVersion: v1
kind: Service
metadata:
  name: a-rest-svc
  namespace: pspd
spec:
  selector: { app: a-rest }
  ports: [ { port: 50061, targetPort: 8000 } ]
