apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: p-rest-ingress
  namespace: pspd
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: pspd-rest.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: p-rest-svc
                port: { number: 80 }
