apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-rest-deploy
  namespace: pspd
spec:
  replicas: 1
  selector: { matchLabels: { app: p-rest } }
  template:
    metadata:
      labels: { app: p-rest }
    spec:
      containers:
        - name: p-rest
          image: p-rest-gateway:local
          imagePullPolicy: IfNotPresent
          env:
            - { name: A_REST, value: "http://a-rest-svc.pspd.svc.cluster.local:50061" }
            - { name: B_REST, value: "http://b-rest-svc.pspd.svc.cluster.local:50062" }
            - { name: PORT, value: "8081" }
          ports: [ { containerPort: 8081 } ]
          readinessProbe:
            tcpSocket: { port: 8081 }
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            tcpSocket: { port: 8081 }
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: p-rest-svc
  namespace: pspd
spec:
  selector: { app: p-rest }
  ports: [ { port: 80, targetPort: 8081 } ]
